-- Lisää DROP TABLE lauseet tähän tiedostoon
-- DROP TABLE IF EXISTS Askare CASCADE;
-- DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Game CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Player CASCADE;